on: [push, workflow_dispatch]
jobs:
  aws_cdk:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    env: 
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests with pytest\
        run: pytest --junitxml=pytest-report.xml
      - name: Configure AWS credentials from repo
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}  
          aws-region: us-east-1
          role-session-name: GitHubActionSession
      - name: Sync files to S3
        run: |
          aws s3 sync ./weather_data s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete --exclude ".git*"
        working-directory: .